### ISSUE TITLE
Dependency injection returns undefined

### ISSUE THREAD

**Issue by drmzio** [bayareawebpro/laravel-micro.js#10]
When [injecting](https://bayareawebpro.github.io/laravel-micro.js/#/docs/injection) `Router` into the `VueRoot` binding, it returns undefined when `VueRoot` gets called from application.js.

#### VueServiceProvider.js
![](https://cl.ly/7cf066106218/%255Bf4bcc7be9c1146368c93acdc6d8051bc%255D_Image%2525202020-02-04%252520at%25252012.26.26%252520AM.png)
#### application.js
![](https://cl.ly/c9b12cf02f4e/Image%2525202020-02-04%252520at%25252012.29.07%252520AM.png)
#### console
![](https://cl.ly/d745e47b28c2/%255Ba71a50f98290952bc5b476f3e0bc9cdc%255D_Image%2525202020-02-04%252520at%25252012.25.33%252520AM.png)

However, the `VueRoot` binding gets resolved without issues.

I followed the VueServiceProvider example from the *laravel-micro-preset* repo. https://github.com/bayareawebpro/laravel-micro-preset/blob/master/src/stubs/micro-app/services/Vue/VueServiceProvider.js

#### webpack.config.js
![](https://cl.ly/585d4e8ad5f0/Image%2525202020-02-04%252520at%25252012.32.50%252520AM.png)

Any idea what the issue could be? I tried everything but no solution. I feel like webpack 4 might be the culprit, but no idea where to start.

**Comment by bayareawebpro** [comment]
I made the mistake of excluding the Webpack compiler rules from the new documentation.

Let me know if this solves it for you:
https://bayareawebpro.github.io/laravel-micro.js/#/docs/install?id=webpack-babel-compiler

**Comment by drmzio** [comment]
@bayareawebpro Works now, thanks! I was excluding all of node_modules..
