### ISSUE TITLE
Singleton method missing

### ISSUE THREAD

**Issue by Garanaw** [bayareawebpro/laravel-micro.js#17]
Not a bug, more like an enhancement:

Today I saw that there is no `singleton` method, but instead a third parameter in the method `bind` to share the instance. I extended the `Container` class with my own and added the method myself, it's merely a proxy to the `bind` method, but only takes two parameters and automatically passes the third as `true`:

```
"use strict";

import Container from 'laravel-micro.js';

export default class Application extends Container
{
    constructor() {
        super();
    }
    
    singleton(alias, binding) {
        return this.bind(alias, binding, true);
    }
}
```

I think this could be a useful addition to the main container

**Comment by bayareawebpro** [comment]
Looks good, I had the same thought as well.  I'll leave this issue open and add a ToDo for the request in the kanban.  The issue will be closed when I have a chance to push out a new release so you'll be notified when this has been implemented and published. 📝

**Comment by bayareawebpro** [comment]
Two new methods have been added to the new release.

- singleton (as suggested)
- factory (inverse of singleton)

`npm update laravel-micro.js`

Enjoy 😄
