### ISSUE TITLE
Coalescing operator not transpiled

### ISSUE THREAD

**Issue by monkeymonk** [bayareawebpro/laravel-micro.js#28]
I was trying `laravel-micro.js` and I'm stuck with

```console
ERROR in ./node_modules/laravel-micro.js/src/Support/Stringable.js 130:42
Module parse failed: Unexpected token (130:42)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     substr(start, end = null) {
|         return new Stringable(
>             this.value.substr(start, end ?? this.length() - start)
|         );
|     }
 @ ./node_modules/laravel-micro.js/src/index.js 7:0-45 14:0-27:1
 @ ./src/js/bootstrap.js
 @ ./src/js/app.js
```

Maybe consider to loose coalescing for now instead of forcing us to transpile `node_modules` or specific module (which is an extra step)?

Did you need/want a pull request for this kind of change?

**Comment by bayareawebpro** [comment]
I'm sorry I just noticed this issue, I've been caring for my mother who had a surgery.  Yes a pull request would be very welcomed, otherwise if you've moved on at this point I can take care of it myself.

**Comment by Garanaw** [comment]
@bayareawebpro I just created a PR for this issue, if you want to have a look at it.

@monkeymonk thanks for reporting this, it looks like we both had our babel plugins including the nullish coalescing operator, so we didn't notice.

**Comment by bayareawebpro** [comment]
#29 Patched and Released. 🎉
